name: nerfactor24
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.6
    - pip
    - numpy
    - scipy
    - matplotlib
    - ipython
    - tqdm
    - pillow
    - opencv
    - pip:
        - tensorflow==2.2
    - cudatoolkit=10.1
    - cudnn=7.6
